# Generated by Django 4.2.11 on 2024-05-05 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_consulta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='estado',
        ),
    ]
